In [1]:
# ======================================================================= #
# Course: Deep Learning Complete Course (CS-501)
# Author: Dr. Saad Laouadi
# 
# 
# =======================================================================
# Module: Binary Classification Practice Exercise
# Topic: Iris Classification with Neural Networks
# =======================================================================
# Learning Objectives:
# 1. Apply classification concepts to a new dataset
# 2. Practice data preparation for multi-class classification
# 3. Build and train a neural network classifier
# 4. Evaluate model performance
# =======================================================================
# Prerequisites:
# - Completion of Titanic Classification lesson
# - Basic understanding of Python and Keras
# - Familiarity with data preprocessing
# =======================================================================
#          Copyright © Dr. Saad Laouadi 2024
# =======================================================================

### Practice Exercise: Iris Flower Classification

Your task is to build a neural network that classifies iris flowers into their respective species.
Follow the steps below and fill in the code where indicated.

In [2]:
# 1. Environment Setup
# ------------------
import numpy as np
import pandas as pd
from tensorflow import keras
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import to_categorical
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [3]:
# Load the Iris dataset
iris = load_iris()
X = iris.data
y = iris.target

In [4]:
# STEP 1: Data Exploration
# -----------------------
# 1. Print the shape of X and y to understand the dataset structure
# 2. Display the first few samples of the data
# 3. Print the target class names (iris.target_names)


# Your code here:
print("Data shape:", X.shape)
print("Target shape:", y.shape)
print("\nSample features:\n", X[:5])
print("\nTarget classes:", iris.target_names)

Data shape: (150, 4)
Target shape: (150,)

Sample features:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]

Target classes: ['setosa' 'versicolor' 'virginica']


In [5]:
# STEP 2: Data Preparation
# -----------------------
# 1. Convert the target variable to categorical format using to_categorical
# 2. Split the data into training and validation sets (use train_test_split)

# Convert targets to categorical format
y_categorical = to_categorical(y,num_classes=3)

# Split the data
X_train, X_val, y_train, y_val = train_test_split(X,y_categorical,test_size=.3,random_state=42)

In [6]:
# STEP 3: Model Building
# ---------------------
# TODO: Create a Sequential model with:
# - Input layer matching feature dimensions
# - One hidden layer with 32 neurons and 'relu' activation
# - Output layer with neurons matching number of classes and 'softmax' activation

In [7]:
# Your code here:
model = Sequential([
    # Add the input layer
    Input(shape=(X.shape[1],)),
    # Add the first hidden layer
    Dense(units=32,activation="relu"),
    # Add the output layer
    Dense(units=3,activation="softmax")
])

# Print model summary
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 3)              │            99 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 259 (1.01 KB)

 Trainable params: 259 (1.01 KB)

 Non-trainable params: 0 (0.00 B)

In [8]:
# STEP 4: Model Compilation
# ------------------------
# Compile the model with:
#       - 'sgd' optimizer
#       - 'categorical_crossentropy' loss
#       - accuracy metric


# Your code here:
model.compile(
    # Add compilation parameters
    optimizer="sgd",
    loss='categorical_crossentropy',
    metrics=['accuracy']
    
)

In [9]:
# STEP 5: Model Training
# ---------------------
# TODO: Train the model with:
# - 25 epochs
# - batch_size of 16
# - Use the validation data created earlier


# Your code here:
history = model.fit(
    # Add training parameters
    X_train,
    y_train,
    epochs=25,
    batch_size=16,
    validation_split=.2,
    verbose=1
    
)

Epoch 1/25
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 56ms/step - accuracy: 0.3788 - loss: 1.8945 - val_accuracy: 0.5238 - val_loss: 1.5650
Epoch 2/25
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5342 - loss: 1.3039 - val_accuracy: 0.3333 - val_loss: 1.1239
Epoch 3/25
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.3536 - loss: 1.1207 - val_accuracy: 0.1429 - val_loss: 1.0609
Epoch 4/25
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.2192 - loss: 1.0861 - val_accuracy: 0.3333 - val_loss: 1.0856
Epoch 5/25
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.2702 - loss: 1.0586 - val_accuracy: 0.3333 - val_loss: 1.0398
Epoch 6/25
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.2931 - loss: 1.0338 - val_accuracy: 0.3333 - val_loss: 1.0178
Epoch 7/25
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.3794 - loss: 1.0083 - val_accuracy: 0.4762 - val_loss: 0.9383
Epoch 8/25
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.2571 - loss: 0.9825 - val_accuracy: 0.1905 - val_loss: 0.9442
E

In [10]:
# Challenge:
# ---------------
# 1. Try adding another hidden layer
# 2. Experiment with different numbers of neurons
# 3. Try using different optimizers (like 'adam')
# 4. Plot the training history (accuracy and loss)
model = Sequential([
    # Add the input layer
    Input(shape=(X.shape[1],)),
    # Add the first hidden layer
    Dense(units=32,activation="relu"),
    # Add the second hidden layer
    Dense(units=64,activation="relu"),
    # Add the output layer
    Dense(units=3,activation="softmax")
])

# Print model summary
model.summary()


model.compile(
    # Add compilation parameters
    optimizer="adam",
    loss='categorical_crossentropy',
    metrics=['accuracy']
    
)
history = model.fit(
    # Add training parameters
    X_train,
    y_train,
    epochs=25,
    batch_size=16,
    validation_split=.2,
    verbose=1
    
)



Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 32)             │           160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 3)              │           195 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,467 (9.64 KB)

 Trainable params: 2,467 (9.64 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/25
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.1888 - loss: 1.1926 - val_accuracy: 0.2857 - val_loss: 1.0569
Epoch 2/25
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.2972 - loss: 1.0640 - val_accuracy: 0.4762 - val_loss: 0.9702
Epoch 3/25
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.2819 - loss: 1.0115 - val_accuracy: 0.5238 - val_loss: 0.9241
Epoch 4/25
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.5168 - loss: 0.9360 - val_accuracy: 0.4286 - val_loss: 0.8863
Epoch 5/25
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6824 - loss: 0.8964 - val_accuracy: 0.5238 - val_loss: 0.8538
Epoch 6/25
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7013 - loss: 0.8569 - val_accuracy: 0.6667 - val_loss: 0.8204
Epoch 7/25
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6921 - loss: 0.8229 - val_accuracy: 0.7619 - val_loss: 0.8017
Epoch 8/25
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8255 - loss: 0.7777 - val_accuracy: 0.7143 - val_loss: 0.7898
Epo

In [11]:
# =======================================================================
# Expected Output:
# - Model should achieve at least 80% validation accuracy
# - Training and validation loss should decrease over time
# - Final model should be able to classify new iris samples accurately
# =======================================================================

In [17]:
model.evaluate(X_val,y_val)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9748 - loss: 0.3528


[0.3437328636646271, 0.9777777791023254]